sudo: required

language: 
  - c
  - java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - sudo apt-get update && sudo apt-get -y install --fix-missing libc6-dev-i386 mosquitto

install:
  - git clone --depth=50 https://github.com/linsong/sedona.git sedona 
  - cd sedona && git checkout -b develop origin/develop && cd ..
  - mkdir -p sedona/src/kits/communityMQTT
  - mv !(sedona) sedona/src/kits/communityMQTT/
  - cd sedona 
  - source ./src/kits/communityMQTT/setup_test.sh 
  - source ./adm/unix/init.sh

script:
  - python adm/makedev.py
