sudo: required

language: 
  - c
  - java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - sudo apt-get update && sudo apt-get -y install --fix-missing libc6-dev-i386 mosquitto

install:
  - git clone -b develop --depth=50 https://github.com/linsong/sedona.git sedona 
  - mkdir -p sedona/src/kits/communityMQTT
  - mv !(sedona) sedona/src/kits/communityMQTT/
  - cd sedona 
  - ./src/kits/communityMQTT/setup_test.sh 

script:
  - ./src/kits/communityMQTT/run_test.sh
# - python adm/makedev.py
